version: '3.8'
services:
  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: optoviy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    command: -c 'listen_addresses=*'
    restart: unless-stopped
    ports:
      - "5432:5432"  # Публикация порта для доступа с localhost
    volumes:
      - ./infrastructure/db/create-db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
