server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://service-db/optoviy
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://service-db/optoviy
    user: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
