server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/optoviy
    username: postgres
    password: root
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/optoviy
    user: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

