version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: b-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgres/data:z
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

volumes:
  postgres_data: